Usage example
BuddahLD/e3kit-usage pull request #1
Opened 2019-10-15 10:37 UTC by BuddahLD

Check MainActivity class only (it's main usage example for now)

2019-10-15 10:51 UTC, SanjoDeundiak requested changes

2019-10-15 10:51 UTC, SanjoDeundiak commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +     * 3) User wants to Sign Up;
4) Sign out

2019-10-15 10:51 UTC, SanjoDeundiak commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +            flowOne()
Descriptive naming should be used

2019-10-15 10:51 UTC, SanjoDeundiak commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +    fun e3kitInitPoint() {
Source code should be somehow tied to actual UI actions, to understand when it should be called

2019-10-15 10:51 UTC, SanjoDeundiak commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +                                // You get here if there's already private key backup present in the
So, what develop is gonna do here?

2019-10-15 10:51 UTC, SanjoDeundiak commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +                                // You get here if there no private key has been found locally.
So, what develop is gonna do here?

2019-10-15 10:51 UTC, SanjoDeundiak commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +                    // e3kit user with provided identity has been already registered.
So, what develop is gonna do here?

2019-10-15 10:51 UTC, SanjoDeundiak commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +                    // This exception means that the private key is already present on the device
So, what develop is gonna do here?

2019-10-15 10:51 UTC, SanjoDeundiak commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +                    // This exception could be thrown if there was an exception while generating
So, what develop is gonna do here?

2019-10-15 10:51 UTC, SanjoDeundiak commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +                                // Don't forget to re-fetch current user's public key for other users
This happens automatically

2019-10-15 10:51 UTC, SanjoDeundiak commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +                                // New public key has been published to the Virgil Cards service.
Update backup?

2019-10-15 10:51 UTC, SanjoDeundiak commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +                                    // rotatePrivateKey function can rotate keys only if there's no private key present
So, what develop is gonna do here?

2019-10-15 10:51 UTC, SanjoDeundiak commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +                                    // Thrown if EThree#rotatePrivateKey is called before EThree#register.
So, what develop is gonna do here?

2019-10-15 10:51 UTC, SanjoDeundiak commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +                                    // This exception could be thrown if there was an exception while generating
So, what develop is gonna do here?

2019-10-16 09:50 UTC, Ogerets requested changes

2019-10-16 09:50 UTC, Ogerets commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +    val jwtGenerator = JwtGenerator(
jwtGenerator was not used anywhere here

2019-10-24 11:03 UTC, BavovnaIsTaken commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +                    // This exception could be thrown if there was an exception while generating
it's written in the comment

2019-10-24 11:06 UTC, BavovnaIsTaken commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +                                // Don't forget to re-fetch current user's public key for other users
how?)

2019-10-24 11:16 UTC, BavovnaIsTaken commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +                                // New public key has been published to the Virgil Cards service.
added as a hint, because user haven't had a backup for some reason and there's chance that she doesn't want yet

2019-10-24 11:16 UTC, BavovnaIsTaken commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +                                    // rotatePrivateKey function can rotate keys only if there's no private key present
it's written in the comment

2019-10-24 11:23 UTC, BavovnaIsTaken commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +                                    // This exception could be thrown if there was an exception while generating
it's written in the comment

2019-10-24 11:33 UTC, Ogerets requested changes

2019-10-24 11:33 UTC, Ogerets commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +    val apiKey = virgilCrypto.importPrivateKey(privateKeyData.data).privateKey
Wasn't used

2019-10-24 11:33 UTC, Ogerets commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +     * 4) Sign Out
User wants to Sign Out* 
(simular to other variants)

2019-10-24 11:37 UTC, Ogerets commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +     * For example you can use Firebase:
Do we really need to add examples of Firebase? We'll need to keep track on Firebase updates and update this usage.

2019-10-24 11:41 UTC, Ogerets requested changes

2019-10-24 11:41 UTC, Ogerets commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +        // context can be any. (e.g. MainActivity's context, Application's context)
Comments should have same style. First letter should be upper-cased here, I guess.

2019-10-24 11:52 UTC, Ogerets requested changes

2019-10-24 11:52 UTC, Ogerets commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +    val chosenSignIn = Random.nextBoolean()
User can choose sign in and sign up and sign out at same time? Why don't you create some UserState enum with all states and keep single val here with user's state?

2019-10-24 11:52 UTC, Ogerets commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +    val chosenLogOut = Random.nextBoolean()
SignOut*

2019-10-24 12:10 UTC, BavovnaIsTaken commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +     * For example you can use Firebase:
No, we don't. But on the other hand it's a good example, as for me. Maybe we can specify version of Firebase used in this comment. But generally - we can remove it. The only thing that concerns me that this usage should be well-understandable, and example helps with that, I think

2019-10-24 12:13 UTC, BavovnaIsTaken commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +    val chosenSignIn = Random.nextBoolean()
why should we care about `variables just to avoid compiler errors` ?
(user's state can be any -  we don't know which)

2019-10-24 12:15 UTC, BavovnaIsTaken commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +    val chosenSignIn = Random.nextBoolean()
everything above `Beginning of usage example with exceptions description` is not usage example itself

2019-10-24 12:41 UTC, Ogerets commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +    val chosenSignIn = Random.nextBoolean()
But you use these variables below `Beginning of usage example with exceptions description` in a way they all can be true or false at the same time, which is unexceptable for real app.

2019-10-24 12:41 UTC, Ogerets commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +    val chosenSignIn = Random.nextBoolean()
> (user's state can be any - we don't know which)

Yes, it's still should be randomized, but valid.

2019-10-24 12:43 UTC, Ogerets requested changes

2019-10-24 12:43 UTC, Ogerets commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +        // context can be any. (e.g. MainActivity's context, Application's context)
Next line should be fixed too

2019-10-24 12:55 UTC, BavovnaIsTaken commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +    val chosenSignIn = Random.nextBoolean()
I got your point, but I don't get why should we make if more complex, while we need just the name of a variable (we can remove all these fields at all. I left them there just for IDE to avoid error highlights in code)
We will share only code below the `Beginning of usage example with exceptions description`

2019-10-24 12:56 UTC, BavovnaIsTaken commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +    val chosenSignIn = Random.nextBoolean()
it's not a working sample

2019-10-24 13:20 UTC, Ogerets requested changes

2019-10-24 13:20 UTC, Ogerets commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +                // You have to decide to ask a user or to backup the private key automatically.
You have to decide whether ask user to backup private key or do it automatically*

2019-10-24 13:20 UTC, Ogerets commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +                                // You get here if there's already private key backup present in the
You get here if there's already private key backuped in the Virgil Cloud with current user's identity*

2019-10-24 13:20 UTC, Ogerets commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +                                // authorization system, because Sign Up means that user haven't
... means that user haven't registered yet..*

We definately need Rebeca review on spelling.

2019-10-24 13:20 UTC, Ogerets commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +                                // had registered yet (neither in your auth system nor it e3kit).
... nor **in** e3kit...

2019-10-24 13:20 UTC, Ogerets commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +                                // You get here if there's no private key has been found locally.
You get here if there's no private key locally*
or 
You get here if no private key is found locally*

2019-10-24 13:20 UTC, Ogerets commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +                    // a user with the same identity (re-register) - you can call EThree#unregister
User can just call rotatePrivateKey instead of two calls unregister and register.

2019-10-24 13:20 UTC, Ogerets commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +                    // It's impossible to get this exception while using e3kit only. But you could
Wrong. Key check goes before alreadyRegistered check, so just calling register twice will return this error without manually saving key.

2019-10-24 13:20 UTC, Ogerets commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +                                // Don't forget to re-fetch current user's public key for other users
Honestly, I can't understand what this comment is saying. Who should re-fetch and whom keys?

2019-10-24 13:20 UTC, Ogerets commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +                                    // Thrown if EThree#rotatePrivateKey is called before EThree#register.
Can be thrown after unregister also

2019-10-24 13:20 UTC, Ogerets commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +                                    // EThree#register has finished successfully.
or successfull unregister

2019-10-24 13:20 UTC, Ogerets commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +                    // Ask other password and try again to restore private key.
I guess, we need to add a comment, that this can't be done faster then in 2 sec.
(until it will be finally fixed on backend)

2019-10-24 13:20 UTC, Ogerets commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +                    // EThree#restorePrivateKey function can restore private key only if there's no one present
... only if there's no private key locally. But it's already present...*

2019-10-24 13:20 UTC, Ogerets commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +                } else if (throwable is PrivateKeyPresentException) {
I can't find in code this exception. I guess we do not check it.

2019-10-24 13:23 UTC, Ogerets commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +     * For example you can use Firebase:
> Maybe we can specify version of Firebase used in this comment

At least

2019-10-24 13:24 UTC, Ogerets commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +    val chosenSignIn = Random.nextBoolean()
> We will share only code below the `Beginning of usage example with exceptions description`

But you use these variables below `Beginning of usage example with exceptions description` in a way they all can be true or false at the same time, which is unexceptable for real app.

2019-10-24 13:27 UTC, BavovnaIsTaken commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +    val chosenSignIn = Random.nextBoolean()
just copy and paste this sample into a text editor and delete everything above `Beginning of usage example with exceptions description`, can it be now anything? yes, but we don't know which particular case, because it's input from outside

2019-10-24 13:30 UTC, Ogerets commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +    val chosenSignIn = Random.nextBoolean()
This code is BELOW `Beginning of usage example with exceptions description` and it is written in a way when user can have multiple states. And developers will copy-paste it.
```
if (userSignedIn) { // It's up to developer to know whether user is Signed In.
    userAlreadySignedIn()
} else {
     if (chosenSignIn) {
         userWantsToSignIn()
     } else if (chosenSignUp) {
         userWantsToSignUp()
     }
}
```

2019-10-24 13:31 UTC, Ogerets commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +    val chosenSignIn = Random.nextBoolean()
This is what i meant

2019-10-24 13:33 UTC, Ogerets commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +    val chosenSignIn = Random.nextBoolean()
On other hand theoretically, apps will triger those functions on ui actions mostly

2019-10-24 13:33 UTC, BavovnaIsTaken commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +                                // You get here if there's no private key has been found locally.
let's leave grammar to Matheus and Rebecca

2019-10-24 13:35 UTC, Ogerets commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +    val chosenSignIn = Random.nextBoolean()
I just think it won't bring complexity. It will only simplify all those if elses to single switch

2019-10-24 13:36 UTC, Ogerets commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +                                // You get here if there's no private key has been found locally.
We should fix what we can on this stage. There is a chance they will miss smth

2019-10-24 13:37 UTC, BavovnaIsTaken commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +                    // a user with the same identity (re-register) - you can call EThree#unregister
I don't think `rotatePrivateKey` usage will be correct because this is Sign Up flow, so you have to revoke old card, then publish new one. As it's a different user, or why would the same user Sign Up again?

2019-10-24 13:40 UTC, Ogerets commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +                    // a user with the same identity (re-register) - you can call EThree#unregister
If he has card registered with same identity it's not a different user.

2019-10-24 13:54 UTC, BavovnaIsTaken commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +                                    // Thrown if EThree#rotatePrivateKey is called before EThree#register.
Can't answer the `Honestly, I can't understand...` comment right there, so the answer here:
It should mean that - developer should not forget to re-fetch public key of current user after rotate on other users' devices if they have had chat with him.

`Can be thrown after unregister also` yes, but we're in result of `rotatePrivateKey` function now.

2019-10-24 13:55 UTC, BavovnaIsTaken commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +                                    // EThree#register has finished successfully.
but we're in `rotatePrivateKey` function and describing it's Exceptions

2019-10-24 14:04 UTC, BavovnaIsTaken commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +                } else if (throwable is PrivateKeyPresentException) {
https://github.com/VirgilSecurity/virgil-e3kit-kotlin/blob/2a3fc0f4c1ee43a87934d6a806c2d6696695c008/ethree-common/src/main/java/com/virgilsecurity/android/common/exception/KeyExceptions.kt#L52

2019-10-24 14:09 UTC, Ogerets commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +                                    // Thrown if EThree#rotatePrivateKey is called before EThree#register.
> Can be thrown after unregister also yes, but we're in result of rotatePrivateKey function now.

So what? If user unregistered already, then rotatePrivateKey could throw this error

2019-10-24 14:11 UTC, BavovnaIsTaken commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +     * For example you can use Firebase:
You know.. I'll remove Firebase references. Let's just leave some *authorization* system and that's all

2019-10-24 14:13 UTC, Ogerets commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +                                // Don't forget to re-fetch current user's public key for other users
Sanjo is right, updating cached cards happens automatically. But since it's in background we need to leave such comment for them. I wish it be more clear) Maybe split it to several sentences?

2019-10-24 14:14 UTC, Ogerets commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +                                    // EThree#register has finished successfully.
So what? If user unregistered already, then rotatePrivateKey could throw this error

2019-10-24 14:14 UTC, BavovnaIsTaken commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +    val chosenSignIn = Random.nextBoolean()
but userSignedIn, chosenSignIn, chosenSignUp won't compile because it will be undefined.
I can change it to switch just to make it look more neat - `if` inside `if` looks a little bit odd

2019-10-24 14:15 UTC, Ogerets commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +                } else if (throwable is PrivateKeyPresentException) {
Exception itself is present. I mean I we don't throw it in restorePrivateKey call

2019-10-24 14:17 UTC, Ogerets commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +    val chosenSignIn = Random.nextBoolean()
> but userSignedIn, chosenSignIn, chosenSignUp won't compile because it will be undefined.

There might be one variable above `Beginning of usage example with exceptions description` with random single state to avoid compilation errors

2019-10-24 14:17 UTC, BavovnaIsTaken commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +    val chosenSignIn = Random.nextBoolean()
and yes - ususally those functions/flows will be separate per UI action
but anyway - developer will have to define values of that variables somehow

this approach was mostly about states variables are even odd here, maybe we can move from variables to just comments like // SignUp goes here

why I did like I did - because different flows separated with just comments can lead to copy-paste of all of 3 actions in one Sign Up for example

2019-10-24 14:19 UTC, BavovnaIsTaken commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +                    // a user with the same identity (re-register) - you can call EThree#unregister
Sign Up should not rotate keys
If you want to rotate - go Sign In then rotate

2019-10-24 14:20 UTC, BavovnaIsTaken commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +                                    // Thrown if EThree#rotatePrivateKey is called before EThree#register.
How rotatePrivateKey can throw exception of unregister? what are we talking about?

2019-10-24 14:22 UTC, Ogerets commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +                                    // Thrown if EThree#rotatePrivateKey is called before EThree#register.
`rotatePrivateKey` can throw `UserNotRegisteredException` if user unregistered before.

2019-10-24 14:27 UTC, BavovnaIsTaken commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +                } else if (throwable is PrivateKeyPresentException) {
We do
https://github.com/VirgilSecurity/virgil-e3kit-kotlin/blob/2a3fc0f4c1ee43a87934d6a806c2d6696695c008/ethree-common/src/main/java/com/virgilsecurity/android/common/worker/BackupWorker.kt#L83

2019-10-24 14:27 UTC, Ogerets commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +                    // a user with the same identity (re-register) - you can call EThree#unregister
This way Sign Up should not unregister either? If user has card he need to go sign in.

2019-10-24 14:28 UTC, Ogerets commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +                    // a user with the same identity (re-register) - you can call EThree#unregister
I thought you just give workaround on this case. unregister+register and rotate is almost simular actions. the difference is representation in cloud: will cards be in one chain or not.

2019-10-24 14:29 UTC, Ogerets commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +                } else if (throwable is PrivateKeyPresentException) {
Oh, okay. iOS don't have this error wrapper, that was the problerm

2019-10-24 14:31 UTC, BavovnaIsTaken commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +                                // Don't forget to re-fetch current user's public key for other users
Yes, I don't like this sentence as well. Will change/split it somehow.
How does it happen automatically? If you won't call findUsers - nothing will happen on it's own, doesn't it?

2019-10-24 14:32 UTC, Ogerets commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +    val chosenSignIn = Random.nextBoolean()
> because different flows separated with just comments can lead to copy-paste of all of 3 actions in one Sign Up for example

Why they will be separeted by comments? if-else will just transform to switch statement

2019-10-24 14:35 UTC, BavovnaIsTaken commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +    val chosenSignIn = Random.nextBoolean()
yes yes
I mean I though about comments instead of if-else, nevermind
let's stick to switch for now

2019-10-24 14:36 UTC, Ogerets commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +                                // Don't forget to re-fetch current user's public key for other users
Actually, should happen on [init](https://github.com/VirgilSecurity/virgil-e3kit-x/blob/master/Source/EThree.swift#L197). We have [test](https://github.com/VirgilSecurity/virgil-e3kit-x/blob/master/Tests/VTE006_LookupTests.swift#L124) on that.

2019-10-24 15:01 UTC, BavovnaIsTaken commented on app/src/main/java/com/virgilsecurity/android/e3kitusage/MainActivity.kt
> +                                // Don't forget to re-fetch current user's public key for other users
yes, but we there's case when user is inside of chat with other user who rotated her private key. For cases like this - I left a notice to keep that in mind

2025-05-08 14:53 UTC, closed without merging